services:
  obolonka:
    build:
      context: ./obolonka
    ports:
      - "5173:3000"
    networks:
      - mererza


  backend_troian:
    image: vitaliktroian04/smart-energy-stability:latest
    ports:
      - "6028:8085"
    restart: always

  pokazovaSlurzba:
    image: bondarenkorodion/slurzba1
    ports:
      - "3000:3000"
    networks:
      - mererza

  backend_yaroslav:
    image: yaroslav333/my-backend:latest
    ports:
      - "6001:5000"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/solar_system
    networks:
      - mererza
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mererza

networks:
  mererza:
    driver: bridge

volumes:
  mongo_data:
